[colors.normal]
black = '#2E3440'
blue = '#5E81AC'
cyan = '#8FBCBB'
green = '#A3D6A9'
magenta = '#B48EAD'
red = '#BF616A'
white = '#D8DEE9'
yellow = '#EBCB8B'

[colors.bright]
black = '#4C566A'
blue = '#81A1C1'
cyan = '#88C0D0'
green = '#A3BE8C'
magenta = '#BE9DB8'
red = '#C5727A'
white = '#ECEFF4'
yellow = '#EFD49F'

[colors.primary]
background = '#242933'
foreground = '#BBBDAF'

