[colors.bright]
black = "0x626262"
blue = "0xadd4fb"
cyan = "0x87d7d7"
green = "0x87af87"
magenta = "0xffafaf"
red = "0xd75f87"
white = "0xe4e4e4"
yellow = "0xffd787"

[colors.normal]
black = "0x4e4e4e"
blue = "0x85add4"
cyan = "0x87afaf"
green = "0x5f865f"
magenta = "0xd7afaf"
red = "0xd68787"
white = "0xd0d0d0"
yellow = "0xd8af5f"

[colors.primary]
background = "0x3a3a3a"
foreground = "0xd0d0d0"

